spring:
  # 开发环境数据源配置
  datasource:
#    driver-class-name:
    url: jdbc:mysql://localhost:3306/haedal_earn_borrow?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  # 开发环境Redis配置
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 0