spring:
  # 开发环境数据源配置
  datasource:
#    driver-class-name:
    url: jdbc:mysql://localhost:3306/haedal_earn_borrow?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 关键：修复 Swagger UI 404 问题（2.6+ 必须配置）
  # 开发环境Redis配置
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 0

springdoc:
  # 扫描 Controller 所在包
  packages-to-scan: com.sui.haedal.rest
  # Swagger UI 访问路径（默认 /swagger-ui/index.html，可自定义）
  swagger-ui:
    path: /swagger-ui.html
    # 接口排序：按方法名（GET/POST 或 字母）
    operationsSorter: method
  # OpenAPI JSON 文档路径
  api-docs:
    path: /v3/api-docs
    enabled: true
