spring:
  profiles:
    active: dev  # 默认激活开发环境（可改为test/prod）
  application:
    name: haedal-server

server:
  port: 9102
  servlet:
    context-path: /haedal
# MyBatis-Plus公共配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.sui.haedal.model
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.example.demo.mapper: debug  # Mapper接口日志级别
